steps:
  # 🔨 Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/project-2713f58c-e744-43b3-a3d/exemplo-backend/backend:latest',
      '.'
    ]

  # 📦 Push para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/project-2713f58c-e744-43b3-a3d/exemplo-backend/backend:latest'
    ]

  # 🚀 Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'exemplo-backend',
      '--image', 'us-central1-docker.pkg.dev/project-2713f58c-e744-43b3-a3d/exemplo-backend/backend:latest',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'us-central1-docker.pkg.dev/project-2713f58c-e744-43b3-a3d/exemplo-backend/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY