steps:
  # 🔐 pegar chave
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-ssh-key'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest --secret=gcp-deploy-key > /workspace/id_rsa
        chmod 600 /workspace/id_rsa

  # 🚀 deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: bash
    args:
      - -c
      - |
        ssh -i /workspace/id_rsa \
            -o StrictHostKeyChecking=no \
            anderson@IP_DA_VM "
              cd /home/anderson/backend &&

              git pull &&

              source venv/bin/activate &&

              pip install -r requirements.txt &&

              pkill gunicorn;

              nohup gunicorn -b 0.0.0.0:8080 app:app > app.log 2>&1 &
            "

options:
  logging: CLOUD_LOGGING_ONLY